on:
  push:
    tags:
      - 'v*'
name: Publish Release
jobs:

  # Build a tagged version
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build Docker Image
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Parse git tag as a version string
    - id: get-version
      run: |
        version=$(echo "${{ github.ref }}" | cut -d / -f 3)
        echo "::set-output name=version::$version"

    - run: echo "${{steps.get-version.outputs.version}}"

    # Runs a single command using the runners shell
    - name: Publish to registry
      uses: elgohr/Publish-Docker-Github-Action@3.02
      env:
        NODE_ENV: production
        DOCKER_BUILDKIT: 1
      with:
        name: ${{ github.repository }}
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REGISTRY_SECRET }}
        buildargs: GITHUB_SHA=${{ github.sha }}
        registry: docker.pkg.github.com
        tags: "latest,${ {steps.get-version.outputs.version }}"
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
